name: Deploy-VM-Windows
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with: 
          host: 99.60.91.9
          username: Eagle3DStreaming
          key: ${{ secrets.PRV_KEY_VM }}
          script: |
            cd C:/wolf/E3DS-Iframe-Demo
            git pull
      