name: Deploy-VM-React
on:
  push:
    branches:
      - staging_iframe_react
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRV_KEY_VM }}
          known_hosts: "Something"
      - name: Adding known_hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST_VM }} >> ~/.ssh/known_hosts
      - run: ssh -tt ubuntu@${{ secrets.SSH_HOST_VM }} 'cd iframe_react; cd E3DS-Iframe-Demo; git stash push -m "Stashed by Actions"; git pull; cd react-eagle-demo; npm run build; /home/ubuntu/.nvm/versions/node/v12.18.4/bin/pm2 restart react_iframe'
      - name: Notify on telegram
        run: |
          curl --request POST \
            --url http://notifications.eagle3dstreaming.com:8080/message_sent \
            --header 'Content-Type: application/json' \
            --data '{
          	"input_chat_id": -680024091,
          	"message": "New update pushed in E3DS-Iframe-Demo repo:  ${{ github.event.head_commit.message }} by ${{ github.event.head_commit.author.name }}"
          }'