name: Deploy-VM-Windows
on:
  push:
    branches:
      - staging_main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRV_KEY_VM }}
          known_hosts: "Something"
      - name: Adding known_hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - run: ssh -tt Eagle3DStreaming@99.60.91.9 'cd iframe&git pull '
      